### ISSUE TITLE
Provide S3 variable examples

### ISSUE THREAD

**Issue by ghost** [r7kamura/mastodon-terraform#5]
What S3-specific variables are required to back this Mastodon instance with out-of-the-box storage?

**Comment by r7kamura** [comment]
Good catch! The feature to create a S3 bucket for uploading files (e.g. user icons, etc.) is not ready yet, but I'm developing it now. I'll let you know in this issue when I finished this work.

**Comment by taohansen** [comment]
@r7kamura Are all variables under _Others_ to be assumed unfinished or if I specify my Amazon Simple Email Service (SES) credentials in the SMTP Terraform variables, will they function?

**Comment by r7kamura** [comment]
Done at https://github.com/r7kamura/mastodon-terraform/issues/18
